### ISSUE TITLE
Write a chapter on community manager self-care

### ISSUE THREAD

**Issue by semioticrobotic** [theopensourceway/guidebook#70] opened 2020-04-08 19:48 UTC
Compose a guidebook chapter explaining the importance of community manager self-care, with tactics and resources for maintaining healthy community management behaviors.

In #69, contributor @samus-aran proposed an excellent overview of this material. Let's consider *beginning* this work as a chapter and broadening to an entire *section* of chapters if a single chapter grows large enough to warrant.

**Comment by semioticrobotic** [comment] 2020-04-08 19:51
Tagging @samus-aran here as intended lead author.

**Comment by quaid** [comment] 2020-04-09 16:03
@semioticrobotic I'm not entirely clear how we want assignments to work, but I think your barrier is that in this project (config or just the way things are?) the assignee needs to be a member of the project. I just invited her, so we'll see if that works.

I think that may be a "way things are", that you can only assign issues to people who are project members. I don't think there needs to be a barrier to being a project member other than interest (ask for it, say yes to offer).

**Comment by quaid** [comment] 2020-04-09 16:13
We just saw a presentation by @mary-grace on "Community Manager burnout". I took these notes, which are incomplete I'm sure but largely capture the essence of things. There are some quite useful bits in here, such as the five signs of pending burnout.
* Burnout categorized by WHO, cf slowly cooked to death, thousand papercuts (not noticing how bad things are until it's too late)
* WHO - chronic workplace stress characterized by:
  - feelings of energy depletion or exhaustion
  - increased mental distance from one's job, or feelings of negativism or cynicism related to one's job
  - reduced professional efficacy
* Not one-off, easily fixed.
  - chronic
  - difficult to get out of
  - can turn into deeper depression
    - WHO classified as lead to or exacerbate existing issues
* Tech susecptible due to 24x7 clock

5 causes of burnout -- 
These are things you can watch, ask for changes around to prevent burnout
1. Lack of Control
   - decisions made without our input
   - things difficult in the community e.g. CoC violations
   - can't control the people around us
1. Unfairness
   - responsible for too many things
   - always lands on your plate
1. Insufficient Reward
   - can be salary/comp
   - recognition, in community or org
1. Work Overload
   - not being to stop and put focus on one specific project
1. Lack of Community
   - ironic
   - surrounded with those we are taking care of, while being forced or feeling forced to neglect our own communities

13m search results showing "burnout community managers" shows this has been an exponentially growing discussion and need now being addressed. More search results likely due to:
- writing about it more
- looking for more help
- big problem, yes more resources, but recognizing is the first part of solving

What can I do about it? (for individuals)
1. Put on your oxygen mask first -- if we aren't getting enough O2, we aren't going to be able to help others
   - be selfish, it helps you be selfless
1. Step away from the work
   - Learn to say no
   - Get your workload reprioritized to take things off
1. Take time when you are sick
   - mentally, physically
   - medical issues that deserve attention that a medical problem get
   - insurance policy may have more resources
1. Find our own communities
   - ones that work FOR us
   - non-tech related may be a good idea
   - people who share similar experiences or interests

What can I do about it? (for managers)

1. Schedule 1:1s
   - regular (weekly, bi-weekly)
   - not about current work but check-in about how they are feeling about work
     - impact
     - too much on their plate
     - what are the motivated vs required to do
1. Mistakes will happen
   - blamless post mortems
     - "Accelerate" book recommendation
   - conversations about how to do things better in the future
   - how to best handle them going forward
   - retrospective about what is going well/not going well
     - team, manager, org
1. Encouraging staff to take time off
   - own health, health of team
     - take time off to recover, better able to focus and take care of community when working
1. Manager is the umbrella
   - help prioritized, de-prioritize
   - shield them from work they shouldn't be loaded with
   - resources and time needed to do work expected

The Dark Side of Community Management
- **Passion** is what drives you and gives you life meaning.
- **Obsession** happens when you are fixated on sometihg else, forsaking all rest.
- **Understand the difference** between passion and obsession to change your thoughts and actions.
- **Find balance** by cultivating other interests offline.

Resources
- "Overwhelmed"
- (long list, need to get the original slides instead)

Q&A with community managers
- talk about what you are feeling, get clarity with a trusted peer before talking with your manager, if needed
- as actual medical condition, can be treated
- stepping away, when possible
- getting back to 100% can be a long-tail
  - different for everyone
  - taking initial time off to figure out what is going on and causing
  - figuring out root causes, so you can get out of it "all justme"
- keeping an eye out for teammates
  - what do you notice
  - just seeing
  - taking time to connect
  - Dave: may provoke defensive reaction, be there for getting through that
  - Bryan: "you are doing so much, want to make sure this is OK"
    - good for managers to track this one
- what do you do when we're all in the big mix
  - have a place for everyone so it's not one person doing the emotional labor
  - recognizing
  - having a space for all to openly discuss
  - proactively lowering expectations
- venting
  - be able, be OK to show frustrations without it always being solved
  - Mary: "Do you just need to vent to a sympathetic ear or are you looking for solutions?"
  - Dave: vent shows energy and engagement, not necc a sign of burnout
  - Mary: look more for apathy as a sign of burnout
- the feeling
  Josh: "everything is shit" i.e. when the things you used to love are things you now hate, you are skirting if not at burnout
- Burnout comes from many things
  - relatively stressful job + outside of job stress
    - a workload once fine with can turn into a burnout
    - your only choice may be to reduce the work side
  - some groups are cutting OKRs in half, for example
  - "the workload that was once fine, likely won't be"
  - some people need work unloaded or normally loaded, depending case-by-case to see what people really need (more or less)
- taking the 'manager' POV is not just for managers
  - team leads, or community leaders can recognize and try to do something
    - Aleksandra: such as helping someone do a new role when they are burning out of that role
  - Josh: experience of asking someone to take time off from responding to new users, better for their mental health, and then it gives room for others to step in to answer.
    - Get help from other senior contributors, stage an intervention
    - set expectations for the role, levels so people can progress up and mentor others

Audience suggested resources
- Short comedy video on what empathy means - "It's not about the nail": https://www.youtube.com/watch?v=-4EDhdAHrOg
- "No Hard Feelings: The Hidden Power of Embracing Emotions at Work": https://www.amazon.com/No-Hard-Feelings-Embracing-Emotions/dp/0525533834

**Comment by samus-aran** [comment] 2020-04-13 16:33
Just a quick mention here that above is a fantastic overview of the presentation (I believe I'm looking at the same one "The Care and Monitoring of You"). :+1: 

Some additional resources:
https://burnout.io/en/latest/index.html
https://burnout.io/en/latest/furtherReading.html
Also reading "The Business Value of Developer Relations: How and Why Technical Communities Are Key To Your Success - Mary Thengvall (Mary Grace)" section about burnout

**Comment by lmaffeo** [comment] 2020-04-13 20:58
Love this idea, @semioticrobotic. Ashley McNamara's keynote at ATO last year - [The Thing About Burnout](https://www.youtube.com/watch?v=-TVdRgT2j54) - would be a great source for this chapter.

**Comment by vmbrasseur** [comment] 2020-04-13 23:09
Decloaking for a moment:

No general objections to the idea of the chapter. However, as this would be walking the fine line of health advice, it's probably best to enlist a mental health professional to write/assist. The advice of well-meaning amateurs can be problematic.

**Comment by mary-grace** [comment] 2020-04-15 01:02
I completely agree! I talked with @samus-aran about this on Monday as well. Any suggestions I give in my book or in any talks are always framed with "I'm not a medical professional." I'm simply speaking from personal experience in the community manager role and know personally just how prevalent of a problem burnout can be for this particular subset of tech professionals. The tips I give are far more about how to manage pre-burnout symptoms and what Ash and I talked about at more depth included ways to make sure moderators have the appropriate training (e.g. https://www.mentalhealthfirstaid.org/) to handle any issues within their communities.

**Comment by vmbrasseur** [comment] 2020-04-15 01:07
While I respect that, even advice prefaced with "I'm not a medical professional" can still be interpreted as medical advice by the audience. Best to play it safe with such things and collaborate with someone who can say "I _am_ a medical professional." IME, if you ask them they're very happy to help.

**Comment by samus-aran** [comment] 2020-04-16 13:21
@vmbrasseur I would very much agree with that statement. I don't know at this very moment in time if there would be any barriers to ask a medical or healthcare professional to collaborate in the context of a guide such as this but that shouldn't stop the process of requesting for input. I personally would like to see a sub-section that details at a high level a where-to-go-from-here if seeking official medical advice supported by the medical professional(s) input. However, we need to ensure that it is generic enough, not specific US based practises/support groups, due to the global audience. 

On the more conservative side and not getting too ahead of ourselves, having a health care advisor would certainly be a plus for this section if not a minimum if possible but not a current blocker to begin the chapter. Now sourcing that professional is another challenge... Anyone have any referrals or those that specifically deal with online community managers or tech?

**Comment by quaid** [comment] 2020-04-23 15:52
This is such a thoughtful discussion, I thank all of you. I appreciate us taking care of each other, ourselves, and others not present, all in the process of talking about writing about taking care of ... Using our own best practices to do this thing is one of my favorite recursive pleasures of this project.

I think @vmbrasseur's point highlights that there are going to be two types of content in this guide -- where community architects/managers hold the experience, and where other professions hold the experience.

For the latter, we would normally/ideally e.g. have a technical edit of a chapter on code audits by a software engineer, and a legal review of a chapter on choosing a license by an experienced open source software lawyer. Thus is makes sense to follow the equivalent is for a medical or mental health professional to provide review/guidance on the content.

I was talking with Leslie Hawthorn about this the other day; she is this project's mentor and one of our chief champions. We agreed that while we didn't quite know how this will work, we are committed to going this necessary step for this content. It's the right thing to do for any content, and particularly important for one with such interpersonal effects. We'll take the details on "who/how" to the private back channel for discussion, in respect of the sensitivity and unknown nature of this.

**Comment by samus-aran** [comment] 2020-04-30 22:08
Hey just a quick call out to the team @quaid or @semioticrobotic That I'm unable to be assigned to this issue. I believe I need to have write access in order to assign myself, unless a team member wants to assign this to me ^^ (I'll write a quick note on the governance issue on the overall set up of teams of the repo's organisation to help with new assignee/project members)

**Comment by semioticrobotic** [comment] 2020-05-01 13:29
Thanks very much for raising this, @samus-aran. I was able to add you as an assignee on this issue, but agree that's a stopgap action until we can determine the best way to organize access privileges and the like. I'll take a look at the issue you've opened regarding this. Thanks.

**Comment by samus-aran** [comment] 2020-05-14 16:58
Just a quick update that I'm looking to get started on this next week :)

**Comment by quaid** [comment] 2020-06-05 05:32
Just noting here that we'd like to include this chapter in a preview release in a few months, schedule TBD.

**Comment by samus-aran** [comment] 2020-06-25 09:50
A wee update! I'm back to having a completely dedicated schedule for this so this is my priority at the moment :+1: I am aiming for a PR pushed by this time next week. I may push it up earlier with the expectation it's WIP and then add to it to reaching the deadline.

Apologies on the radio silence if it was felt.

**Comment by samus-aran** [comment] 2020-07-02 17:05
Further update, working well on this. Though it has become a bit of a monster. I will reflect upon why I feel this is when the PR is pushed up as well as other points to highlight like references, suggested SMEs etc. I'm just revising the chapter as a whole and converting everything into American-british :wink:. Expect a PR in the next couple of days :+1:

**Comment by semioticrobotic** [comment] 2020-09-11 19:36
Reopened as reaction to automation.

**Comment by quaid** [comment] 2020-09-16 21:24
@samus-aran Just a heads up that I have a solid lead on your SME review plan, and am feeling pretty confident we will land a review in the coming few weeks.

**Closed** 2020-12-08 01:08 UTC
Labels: Avoiding Pitfalls, Chapter, Editorial, Preview chapter, SME needed
